GET http://localhost:3000/subscribers

###

GET http://localhost:3000/subscribers/5d9e19060d3b8f384dd2b830

###

POST http://localhost:3000/subscribers
Content-Type: application/json

{
    "name": "Amazing Person",
    "subscribedToChannel": "Web dev simplified"
}

###

PUT http://localhost:3000/subscribers/5d9e35dce035123a1ea52fa2
Content-Type: application/json

{
    "name": "Amazing AMAZING Person",
     "subscribedToChannel": "Web dev simplified"
}

###

DELETE http://localhost:3000/subscribers/5d9e19060d3b8f384dd2b830


